version: "3.8"

services:
  mssqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql_backend_db
    platform: linux/amd64
    environment:
      - SA_PASSWORD=Witchaphon11221!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
    driver: local
